site_name: Spectralign

theme:
  name: material
  
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_signature_annotations: false
            show_signature: false
            show_source: false
            show_category_heading: true
            merge_init_into_class: true
            summary: true
            docstring_section_style: table
            docstring_style: google
            show_labels: false
        
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

extra_css:
  - style.css
  
nav:
  - Home: index.md
  - API documentation:
    - matcher.md

      